# Generated by Django 5.0.1 on 2024-04-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inproducts_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='pic')),
                ('title', models.TextField(max_length=25)),
                ('des', models.TextField(max_length=25)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='outproducts_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='pic')),
                ('title', models.TextField(max_length=25)),
                ('des', models.TextField(max_length=25)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
