# Generated by Django 5.0.1 on 2024-04-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_inproducts_tbl_outproducts_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpatient_tbl',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='inproducts_tbl',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='outpatient_tbl',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='outproducts_tbl',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
