# Generated by Django 5.0.1 on 2024-04-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_alter_inpatient_tbl_name_alter_inproducts_tbl_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inproducts_tbl',
            name='des',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='outproducts_tbl',
            name='des',
            field=models.TextField(max_length=300),
        ),
    ]
