# Generated by Django 5.0.1 on 2024-04-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0005_payment_tbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_tbl',
            name='buyer',
        ),
    ]
