# Generated by Django 5.0.1 on 2024-04-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0007_outpayment_tbl_rename_payment_tbl_inpayment_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='out_order_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('item', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('adress', models.CharField(max_length=40)),
            ],
        ),
    ]
